CREATE TABLE IF NOT EXISTS sl_armes (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sl_phases_choregraphie (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sl_cibles (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sl_techniques_offensives (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sl_attributs_offensifs (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sl_techniques_defensives (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sl_attributs_defensifs (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sl_preparations (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sl_deplacements (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS user_sl_armes (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, label TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS user_sl_phases_choregraphie (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, label TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS user_sl_cibles (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, label TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS user_sl_techniques_offensives (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, label TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS user_sl_attributs_offensifs (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, label TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS user_sl_techniques_defensives (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, label TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS user_sl_attributs_defensifs (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, label TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS user_sl_preparations (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, label TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS user_sl_deplacements (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, label TEXT NOT NULL);
