CREATE TABLE IF NOT EXISTS offensive (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
DELETE FROM offensive;
INSERT INTO offensive (label) VALUES ('attaque');
INSERT INTO offensive (label) VALUES ('attaque composée');
INSERT INTO offensive (label) VALUES ('feinte');

CREATE TABLE IF NOT EXISTS action (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
DELETE FROM action;
INSERT INTO action (label) VALUES ('batté');
INSERT INTO action (label) VALUES ('banderole');
INSERT INTO action (label) VALUES ('brisé');
INSERT INTO action (label) VALUES ('coup de pointe');
INSERT INTO action (label) VALUES ('coup droit');
INSERT INTO action (label) VALUES ('coup de revers');
INSERT INTO action (label) VALUES ('coupé');
INSERT INTO action (label) VALUES ('contre-dégagement');
INSERT INTO action (label) VALUES ('couronné');
INSERT INTO action (label) VALUES ('couronné revers');
INSERT INTO action (label) VALUES ('dégagement');
INSERT INTO action (label) VALUES ('enlevé');
INSERT INTO action (label) VALUES ('estocade');
INSERT INTO action (label) VALUES ('enrobement');
INSERT INTO action (label) VALUES ('moulinet');
INSERT INTO action (label) VALUES ('pression (jeté)');
INSERT INTO action (label) VALUES ('remise');
INSERT INTO action (label) VALUES ('reprise');
INSERT INTO action (label) VALUES ('riposte');
INSERT INTO action (label) VALUES ('contre-riposte');
INSERT INTO action (label) VALUES ('contre-temps');
INSERT INTO action (label) VALUES ('terrassement');
INSERT INTO action (label) VALUES ('tranché');

CREATE TABLE IF NOT EXISTS defensive (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
DELETE FROM defensive;
INSERT INTO defensive (label) VALUES ('déséquilibre');
INSERT INTO defensive (label) VALUES ('esquive arrière');
INSERT INTO defensive (label) VALUES ('esquive basse');
INSERT INTO defensive (label) VALUES ('esquive en sautant');
INSERT INTO defensive (label) VALUES ('esquive latérale extérieure');
INSERT INTO defensive (label) VALUES ('esquive latérale intérieure');
INSERT INTO defensive (label) VALUES ('invitation');
INSERT INTO defensive (label) VALUES ('parade');
INSERT INTO defensive (label) VALUES ('parade bouclier');
INSERT INTO defensive (label) VALUES ('parade cape');
INSERT INTO defensive (label) VALUES ('parade circulaire');
INSERT INTO defensive (label) VALUES ('parade dague circulaire');
INSERT INTO defensive (label) VALUES ('parade dague directe');
INSERT INTO defensive (label) VALUES ('parade dague semi-circulaire');
INSERT INTO defensive (label) VALUES ('parade de main');
INSERT INTO defensive (label) VALUES ('parade directe');
INSERT INTO defensive (label) VALUES ('parade en croix');
INSERT INTO defensive (label) VALUES ('parade d’opposition');
INSERT INTO defensive (label) VALUES ('parade en cédant');
INSERT INTO defensive (label) VALUES ('parade en double');
INSERT INTO defensive (label) VALUES ('parade semi-circulaire');
INSERT INTO defensive (label) VALUES ('passata di sotto');
INSERT INTO defensive (label) VALUES ('ramassé');

CREATE TABLE IF NOT EXISTS cible (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
DELETE FROM cible;
INSERT INTO cible (label) VALUES ('tête');
INSERT INTO cible (label) VALUES ('épaule');
INSERT INTO cible (label) VALUES ('poitrine');
INSERT INTO cible (label) VALUES ('bras');
INSERT INTO cible (label) VALUES ('cuisse');
INSERT INTO cible (label) VALUES ('flanc');
INSERT INTO cible (label) VALUES ('pied');
INSERT INTO cible (label) VALUES ('tibia');
INSERT INTO cible (label) VALUES ('ventre');

CREATE TABLE IF NOT EXISTS deplacement_attaque (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
DELETE FROM deplacement_attaque;
INSERT INTO deplacement_attaque (label) VALUES ('appel de pied arrière');
INSERT INTO deplacement_attaque (label) VALUES ('appel de pied avant');
INSERT INTO deplacement_attaque (label) VALUES ('balestra');
INSERT INTO deplacement_attaque (label) VALUES ('bond avant');
INSERT INTO deplacement_attaque (label) VALUES ('changement de garde arrière');
INSERT INTO deplacement_attaque (label) VALUES ('changement de garde avant');
INSERT INTO deplacement_attaque (label) VALUES ('contre-volte avant');
INSERT INTO deplacement_attaque (label) VALUES ('demi-marche');
INSERT INTO deplacement_attaque (label) VALUES ('demi-passe avant');
INSERT INTO deplacement_attaque (label) VALUES ('demi-volte avant externe');
INSERT INTO deplacement_attaque (label) VALUES ('demi-volte avant interne');
INSERT INTO deplacement_attaque (label) VALUES ('déplacement latéral externe');
INSERT INTO deplacement_attaque (label) VALUES ('déplacement latéral interne');
INSERT INTO deplacement_attaque (label) VALUES ('fente');
INSERT INTO deplacement_attaque (label) VALUES ('fente inversée');
INSERT INTO deplacement_attaque (label) VALUES ('flèche');
INSERT INTO deplacement_attaque (label) VALUES ('marche');
INSERT INTO deplacement_attaque (label) VALUES ('passe avant');
INSERT INTO deplacement_attaque (label) VALUES ('quart de volte avant externe');
INSERT INTO deplacement_attaque (label) VALUES ('quart de volte avant interne');
INSERT INTO deplacement_attaque (label) VALUES ('redoublement de fente');
INSERT INTO deplacement_attaque (label) VALUES ('retour en garde vers l''avant');
INSERT INTO deplacement_attaque (label) VALUES ('volte avant');

CREATE TABLE IF NOT EXISTS deplacement_defense (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
DELETE FROM deplacement_defense;
INSERT INTO deplacement_defense (label) VALUES ('bond arrière');
INSERT INTO deplacement_defense (label) VALUES ('contre-volte arrière');
INSERT INTO deplacement_defense (label) VALUES ('demi-marche');
INSERT INTO deplacement_defense (label) VALUES ('demi-passe arrière');
INSERT INTO deplacement_defense (label) VALUES ('demi-retraite');
INSERT INTO deplacement_defense (label) VALUES ('demi-volte arrière externe');
INSERT INTO deplacement_defense (label) VALUES ('demi-volte arrière interne');
INSERT INTO deplacement_defense (label) VALUES ('déplacement latéral externe');
INSERT INTO deplacement_defense (label) VALUES ('déplacement latéral interne');
INSERT INTO deplacement_defense (label) VALUES ('passe arrière');
INSERT INTO deplacement_defense (label) VALUES ('quart de volte arrière externe');
INSERT INTO deplacement_defense (label) VALUES ('quart de volte arrière interne');
INSERT INTO deplacement_defense (label) VALUES ('retour en garde vers l''arrière');
INSERT INTO deplacement_defense (label) VALUES ('retraite');
INSERT INTO deplacement_defense (label) VALUES ('volte arrière');

CREATE TABLE IF NOT EXISTS parade_numero (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
DELETE FROM parade_numero;
INSERT INTO parade_numero (label) VALUES ('1');
INSERT INTO parade_numero (label) VALUES ('2');
INSERT INTO parade_numero (label) VALUES ('3');
INSERT INTO parade_numero (label) VALUES ('4');
INSERT INTO parade_numero (label) VALUES ('5');
INSERT INTO parade_numero (label) VALUES ('6');
INSERT INTO parade_numero (label) VALUES ('7');
INSERT INTO parade_numero (label) VALUES ('8');
INSERT INTO parade_numero (label) VALUES ('9');

CREATE TABLE IF NOT EXISTS parade_attribut (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
DELETE FROM parade_attribut;
INSERT INTO parade_attribut (label) VALUES ('haut');
INSERT INTO parade_attribut (label) VALUES ('bas');
INSERT INTO parade_attribut (label) VALUES ('normal');

CREATE TABLE IF NOT EXISTS attaque_attribut (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
DELETE FROM attaque_attribut;
INSERT INTO attaque_attribut (label) VALUES ('interieur');
INSERT INTO attaque_attribut (label) VALUES ('exterieur');
INSERT INTO attaque_attribut (label) VALUES ('inversé');
