CREATE TABLE IF NOT EXISTS offensive (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
DELETE FROM offensive;
INSERT INTO offensive (label) VALUES ('Attaque');
INSERT INTO offensive (label) VALUES ('Feinte');

CREATE TABLE IF NOT EXISTS action (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
DELETE FROM action;
INSERT INTO action (label) VALUES ('Batté');
INSERT INTO action (label) VALUES ('Banderole');
INSERT INTO action (label) VALUES ('Brisé');
INSERT INTO action (label) VALUES ('Coup de pointe');
INSERT INTO action (label) VALUES ('Coupé');
INSERT INTO action (label) VALUES ('Couronné');
INSERT INTO action (label) VALUES ('Couronné revers');
INSERT INTO action (label) VALUES ('Dégagement');
INSERT INTO action (label) VALUES ('Enrobement');
INSERT INTO action (label) VALUES ('Moulinet');
INSERT INTO action (label) VALUES ('Pression (Jeté)');
INSERT INTO action (label) VALUES ('Terrassement');
INSERT INTO action (label) VALUES ('Tranché');

CREATE TABLE IF NOT EXISTS defensive (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
DELETE FROM defensive;
INSERT INTO defensive (label) VALUES ('Déséquilibre');
INSERT INTO defensive (label) VALUES ('Esquive arrière');
INSERT INTO defensive (label) VALUES ('Esquive basse');
INSERT INTO defensive (label) VALUES ('Esquive en sautant');
INSERT INTO defensive (label) VALUES ('Esquive latérale extérieure');
INSERT INTO defensive (label) VALUES ('Esquive latérale intérieure');
INSERT INTO defensive (label) VALUES ('Invitation');
INSERT INTO defensive (label) VALUES ('Parade');
INSERT INTO defensive (label) VALUES ('Parade bouclier');
INSERT INTO defensive (label) VALUES ('Parade cape');
INSERT INTO defensive (label) VALUES ('Parade circulaire');
INSERT INTO defensive (label) VALUES ('Parade dague circulaire');
INSERT INTO defensive (label) VALUES ('Parade dague directe');
INSERT INTO defensive (label) VALUES ('Parade dague semi-circulaire');
INSERT INTO defensive (label) VALUES ('Parade de main');
INSERT INTO defensive (label) VALUES ('Parade directe');
INSERT INTO defensive (label) VALUES ('Parade en croix');
INSERT INTO defensive (label) VALUES ('Parade en cédant');
INSERT INTO defensive (label) VALUES ('Parade en double');
INSERT INTO defensive (label) VALUES ('Parade semi-circulaire');
INSERT INTO defensive (label) VALUES ('Ramassé');

CREATE TABLE IF NOT EXISTS cible (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
DELETE FROM cible;
INSERT INTO cible (label) VALUES ('Tête');
INSERT INTO cible (label) VALUES ('Épaule');
INSERT INTO cible (label) VALUES ('Poitrine');
INSERT INTO cible (label) VALUES ('bras');
INSERT INTO cible (label) VALUES ('Cuisse');
INSERT INTO cible (label) VALUES ('Flanc');
INSERT INTO cible (label) VALUES ('Pied');
INSERT INTO cible (label) VALUES ('Tibia');
INSERT INTO cible (label) VALUES ('Ventre');

CREATE TABLE IF NOT EXISTS deplacement_attaque (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
DELETE FROM deplacement_attaque;
INSERT INTO deplacement_attaque (label) VALUES ('Appel de pied arrière');
INSERT INTO deplacement_attaque (label) VALUES ('Appel de pied avant');
INSERT INTO deplacement_attaque (label) VALUES ('Balestra');
INSERT INTO deplacement_attaque (label) VALUES ('Bond avant');
INSERT INTO deplacement_attaque (label) VALUES ('Changement de garde arrière');
INSERT INTO deplacement_attaque (label) VALUES ('Changement de garde avant');
INSERT INTO deplacement_attaque (label) VALUES ('Contre-Volte avant');
INSERT INTO deplacement_attaque (label) VALUES ('Demi-Marche');
INSERT INTO deplacement_attaque (label) VALUES ('Demi-Passe avant');
INSERT INTO deplacement_attaque (label) VALUES ('Demi-Volte avant externe');
INSERT INTO deplacement_attaque (label) VALUES ('Demi-Volte avant interne');
INSERT INTO deplacement_attaque (label) VALUES ('Déplacement latéral externe');
INSERT INTO deplacement_attaque (label) VALUES ('Déplacement latéral interne');
INSERT INTO deplacement_attaque (label) VALUES ('Fente');
INSERT INTO deplacement_attaque (label) VALUES ('Fente inversée');
INSERT INTO deplacement_attaque (label) VALUES ('Flèche');
INSERT INTO deplacement_attaque (label) VALUES ('Marche');
INSERT INTO deplacement_attaque (label) VALUES ('Passe avant');
INSERT INTO deplacement_attaque (label) VALUES ('Quart de Volte avant externe');
INSERT INTO deplacement_attaque (label) VALUES ('Quart de Volte avant interne');
INSERT INTO deplacement_attaque (label) VALUES ('Redoublement de fente');
INSERT INTO deplacement_attaque (label) VALUES ('Retour en garde vers l''avant');
INSERT INTO deplacement_attaque (label) VALUES ('Volte avant');

CREATE TABLE IF NOT EXISTS deplacement_defense (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
DELETE FROM deplacement_defense;
INSERT INTO deplacement_defense (label) VALUES ('Bond arrière');
INSERT INTO deplacement_defense (label) VALUES ('Contre-Volte arrière');
INSERT INTO deplacement_defense (label) VALUES ('Demi-Marche');
INSERT INTO deplacement_defense (label) VALUES ('Demi-Passe arrière');
INSERT INTO deplacement_defense (label) VALUES ('Demi-Retraite');
INSERT INTO deplacement_defense (label) VALUES ('Demi-Volte arrière externe');
INSERT INTO deplacement_defense (label) VALUES ('Demi-Volte arrière interne');
INSERT INTO deplacement_defense (label) VALUES ('Déplacement latéral externe');
INSERT INTO deplacement_defense (label) VALUES ('Déplacement latéral interne');
INSERT INTO deplacement_defense (label) VALUES ('Passe arrière');
INSERT INTO deplacement_defense (label) VALUES ('Quart de Volte arrière externe');
INSERT INTO deplacement_defense (label) VALUES ('Quart de Volte arrière interne');
INSERT INTO deplacement_defense (label) VALUES ('Retour en garde vers l''arrière');
INSERT INTO deplacement_defense (label) VALUES ('Retraite');
INSERT INTO deplacement_defense (label) VALUES ('Volte arrière');

CREATE TABLE IF NOT EXISTS parade_numero (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
DELETE FROM parade_numero;
INSERT INTO parade_numero (label) VALUES ('1');
INSERT INTO parade_numero (label) VALUES ('2');
INSERT INTO parade_numero (label) VALUES ('3');
INSERT INTO parade_numero (label) VALUES ('4');
INSERT INTO parade_numero (label) VALUES ('5');
INSERT INTO parade_numero (label) VALUES ('6');
INSERT INTO parade_numero (label) VALUES ('7');
INSERT INTO parade_numero (label) VALUES ('8');
INSERT INTO parade_numero (label) VALUES ('9');

CREATE TABLE IF NOT EXISTS parade_attribut (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
DELETE FROM parade_attribut;
INSERT INTO parade_attribut (label) VALUES ('Haut');
INSERT INTO parade_attribut (label) VALUES ('Bas');
INSERT INTO parade_attribut (label) VALUES ('Normal');

CREATE TABLE IF NOT EXISTS attaque_attribut (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
DELETE FROM attaque_attribut;
INSERT INTO attaque_attribut (label) VALUES ('Interieur');
INSERT INTO attaque_attribut (label) VALUES ('Exterieur');
INSERT INTO attaque_attribut (label) VALUES ('Inversé');

