CREATE TABLE IF NOT EXISTS sl_armes (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
DELETE FROM sl_armes;
INSERT INTO sl_armes (label) VALUES ('sabre laser à simple lame');
INSERT INTO sl_armes (label) VALUES ('double sabre laser');
INSERT INTO sl_armes (label) VALUES ('sabre laser cross guard');
INSERT INTO sl_armes (label) VALUES ('tonfa laser');
INSERT INTO sl_armes (label) VALUES ('lance laser');
INSERT INTO sl_armes (label) VALUES ('shoto laser');
INSERT INTO sl_armes (label) VALUES ('deux sabres lasers à simple lame');

CREATE TABLE IF NOT EXISTS sl_phases_choregraphie (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
DELETE FROM sl_phases_choregraphie;
INSERT INTO sl_phases_choregraphie (label) VALUES ('mise en garde');
INSERT INTO sl_phases_choregraphie (label) VALUES ('corps à corps');
INSERT INTO sl_phases_choregraphie (label) VALUES ('déplacements');
INSERT INTO sl_phases_choregraphie (label) VALUES ('lâcher de sabre');
INSERT INTO sl_phases_choregraphie (label) VALUES ('invite / armé');

CREATE TABLE IF NOT EXISTS sl_cibles (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
DELETE FROM sl_cibles;
INSERT INTO sl_cibles (label) VALUES ('arme');
INSERT INTO sl_cibles (label) VALUES ('membres supérieurs');
INSERT INTO sl_cibles (label) VALUES ('membres inférieurs');
INSERT INTO sl_cibles (label) VALUES ('tête');
INSERT INTO sl_cibles (label) VALUES ('tronc');
INSERT INTO sl_cibles (label) VALUES ('épaule');
INSERT INTO sl_cibles (label) VALUES ('hanche');

CREATE TABLE IF NOT EXISTS sl_techniques_offensives (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
DELETE FROM sl_techniques_offensives;
INSERT INTO sl_techniques_offensives (label) VALUES ('attaque de taille');
INSERT INTO sl_techniques_offensives (label) VALUES ('attaque de contre-taille');
INSERT INTO sl_techniques_offensives (label) VALUES ('coup droit');
INSERT INTO sl_techniques_offensives (label) VALUES ('dégagement');
INSERT INTO sl_techniques_offensives (label) VALUES ('coupé');
INSERT INTO sl_techniques_offensives (label) VALUES ('contre-dégagement');
INSERT INTO sl_techniques_offensives (label) VALUES ('feinte');
INSERT INTO sl_techniques_offensives (label) VALUES ('double-engagement');
INSERT INTO sl_techniques_offensives (label) VALUES ('changement d’engagement');
INSERT INTO sl_techniques_offensives (label) VALUES ('attaque composée');
INSERT INTO sl_techniques_offensives (label) VALUES ('estoc');
INSERT INTO sl_techniques_offensives (label) VALUES ('couronné');
INSERT INTO sl_techniques_offensives (label) VALUES ('balayage');
INSERT INTO sl_techniques_offensives (label) VALUES ('remise');
INSERT INTO sl_techniques_offensives (label) VALUES ('riposte');
INSERT INTO sl_techniques_offensives (label) VALUES ('contre-riposte');
INSERT INTO sl_techniques_offensives (label) VALUES ('contre-temps');
INSERT INTO sl_techniques_offensives (label) VALUES ('dérobement');
INSERT INTO sl_techniques_offensives (label) VALUES ('coulé');

CREATE TABLE IF NOT EXISTS sl_attributs_offensifs (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
DELETE FROM sl_attributs_offensifs;
INSERT INTO sl_attributs_offensifs (label) VALUES ('intérieur');
INSERT INTO sl_attributs_offensifs (label) VALUES ('extérieur');
INSERT INTO sl_attributs_offensifs (label) VALUES ('dessus');
INSERT INTO sl_attributs_offensifs (label) VALUES ('dessous');
INSERT INTO sl_attributs_offensifs (label) VALUES ('direct');
INSERT INTO sl_attributs_offensifs (label) VALUES ('indirect');
INSERT INTO sl_attributs_offensifs (label) VALUES ('avec préparation');
INSERT INTO sl_attributs_offensifs (label) VALUES ('simple');
INSERT INTO sl_attributs_offensifs (label) VALUES ('composée');
INSERT INTO sl_attributs_offensifs (label) VALUES ('trajectoire horizontale');
INSERT INTO sl_attributs_offensifs (label) VALUES ('trajectoire verticale');
INSERT INTO sl_attributs_offensifs (label) VALUES ('trajectoire oblique');
INSERT INTO sl_attributs_offensifs (label) VALUES ('sens ascendant');
INSERT INTO sl_attributs_offensifs (label) VALUES ('sens descendant');
INSERT INTO sl_attributs_offensifs (label) VALUES ('trajectoire verticale descendante');
INSERT INTO sl_attributs_offensifs (label) VALUES ('trajectoire oblique descendante');
INSERT INTO sl_attributs_offensifs (label) VALUES ('dedans');
INSERT INTO sl_attributs_offensifs (label) VALUES ('dehors');
INSERT INTO sl_attributs_offensifs (label) VALUES ('dedans dessus');
INSERT INTO sl_attributs_offensifs (label) VALUES ('dedans dessous');
INSERT INTO sl_attributs_offensifs (label) VALUES ('dehors dessus');
INSERT INTO sl_attributs_offensifs (label) VALUES ('dehors dessous');
INSERT INTO sl_attributs_offensifs (label) VALUES ('légère (shim)');
INSERT INTO sl_attributs_offensifs (label) VALUES ('modérée (cho)');
INSERT INTO sl_attributs_offensifs (label) VALUES ('puissante (sai)');
INSERT INTO sl_attributs_offensifs (label) VALUES ('orbite horizontale');
INSERT INTO sl_attributs_offensifs (label) VALUES ('orbite verticale');
INSERT INTO sl_attributs_offensifs (label) VALUES ('orbite majeure');
INSERT INTO sl_attributs_offensifs (label) VALUES ('orbite mineure');

CREATE TABLE IF NOT EXISTS sl_techniques_defensives (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
DELETE FROM sl_techniques_defensives;
INSERT INTO sl_techniques_defensives (label) VALUES ('parade latérale');
INSERT INTO sl_techniques_defensives (label) VALUES ('parade circulaire');
INSERT INTO sl_techniques_defensives (label) VALUES ('parade semi-circulaire');
INSERT INTO sl_techniques_defensives (label) VALUES ('parade diagonale');
INSERT INTO sl_techniques_defensives (label) VALUES ('esquive partielle');
INSERT INTO sl_techniques_defensives (label) VALUES ('esquive totale');

CREATE TABLE IF NOT EXISTS sl_attributs_defensifs (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
DELETE FROM sl_attributs_defensifs;
INSERT INTO sl_attributs_defensifs (label) VALUES ('en opposition');
INSERT INTO sl_attributs_defensifs (label) VALUES ('en cédant');
INSERT INTO sl_attributs_defensifs (label) VALUES ('du tac');
INSERT INTO sl_attributs_defensifs (label) VALUES ('passive');
INSERT INTO sl_attributs_defensifs (label) VALUES ('active');

CREATE TABLE IF NOT EXISTS sl_preparations (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
DELETE FROM sl_preparations;
INSERT INTO sl_preparations (label) VALUES ('engagement');
INSERT INTO sl_preparations (label) VALUES ('prendre l’engagement');
INSERT INTO sl_preparations (label) VALUES ('changer d’engagement');
INSERT INTO sl_preparations (label) VALUES ('invite');
INSERT INTO sl_preparations (label) VALUES ('armé d’engagement');
INSERT INTO sl_preparations (label) VALUES ('armé simple');
INSERT INTO sl_preparations (label) VALUES ('battement');
INSERT INTO sl_preparations (label) VALUES ('pression');
INSERT INTO sl_preparations (label) VALUES ('froissement');
INSERT INTO sl_preparations (label) VALUES ('liement');
INSERT INTO sl_preparations (label) VALUES ('enveloppement');
INSERT INTO sl_preparations (label) VALUES ('opposition');

CREATE TABLE IF NOT EXISTS sl_deplacements (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL);
DELETE FROM sl_deplacements;
INSERT INTO sl_deplacements (label) VALUES ('marche');
INSERT INTO sl_deplacements (label) VALUES ('marche en trois temps');
INSERT INTO sl_deplacements (label) VALUES ('marche inversée');
INSERT INTO sl_deplacements (label) VALUES ('retraite');
INSERT INTO sl_deplacements (label) VALUES ('retraite inversée');
INSERT INTO sl_deplacements (label) VALUES ('changement de garde');
INSERT INTO sl_deplacements (label) VALUES ('changement de garde arrière');
INSERT INTO sl_deplacements (label) VALUES ('changement de garde avant');
INSERT INTO sl_deplacements (label) VALUES ('changement de garde latéral');
INSERT INTO sl_deplacements (label) VALUES ('retour en garde');
INSERT INTO sl_deplacements (label) VALUES ('reprise de garde');
INSERT INTO sl_deplacements (label) VALUES ('pas latéral');
INSERT INTO sl_deplacements (label) VALUES ('passe latérale');
INSERT INTO sl_deplacements (label) VALUES ('fente');
INSERT INTO sl_deplacements (label) VALUES ('fente avant');
INSERT INTO sl_deplacements (label) VALUES ('demi-fente');
INSERT INTO sl_deplacements (label) VALUES ('fente arrière');
INSERT INTO sl_deplacements (label) VALUES ('fente latérale');
INSERT INTO sl_deplacements (label) VALUES ('fente diagonale');
INSERT INTO sl_deplacements (label) VALUES ('fente avant-droite');
INSERT INTO sl_deplacements (label) VALUES ('fente avant-gauche');
INSERT INTO sl_deplacements (label) VALUES ('fente arrière-droite');
INSERT INTO sl_deplacements (label) VALUES ('fente arrière-gauche');
INSERT INTO sl_deplacements (label) VALUES ('fente inversée avant');
INSERT INTO sl_deplacements (label) VALUES ('fente inversée arrière');
INSERT INTO sl_deplacements (label) VALUES ('redoublement');
INSERT INTO sl_deplacements (label) VALUES ('passe avant');
INSERT INTO sl_deplacements (label) VALUES ('passe arrière');
INSERT INTO sl_deplacements (label) VALUES ('bond avant');
INSERT INTO sl_deplacements (label) VALUES ('bond arrière');
INSERT INTO sl_deplacements (label) VALUES ('volte');
INSERT INTO sl_deplacements (label) VALUES ('contre-volte');
INSERT INTO sl_deplacements (label) VALUES ('demi-volte');
INSERT INTO sl_deplacements (label) VALUES ('volte sautée');
INSERT INTO sl_deplacements (label) VALUES ('glissade');
INSERT INTO sl_deplacements (label) VALUES ('roulade');
